import Navbar from '@/components/navbar/headerMobile'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './provider'
import Menu from '@/components/navbar/menu'
import HeaderMobile from '@/components/navbar/headerMobile'
import Header from '@/components/navbar/header'
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  manifest: "/manifest.json",
  title: 'Portfolio Ivana Kowalczuk',
  description: 'Generated by create next app',
  viewport: "width=device-width, initial-scale=1.0",
  icons:{
    apple: "/icon.png"
  },
  themeColor: "#000"

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
 
    <html  lang="es" >
      <body className='flex flex-col justify-between  '>
        <HeaderMobile/>
        <Header/>
        <div className='mx-auto lg:w-11/12 '>
        <Providers >
        {children}
        </Providers>
        </div>
        <Footer/>
      </body>
    </html>
   
  )
}
