import Navbar from '@/components/navbar/page'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio Ivana Kowalczuk',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      
      <body className={inter.className}>
        <div className='h-screen'>
         <Navbar/>
      
      <div className='mt-8 mx-auto p-4'>
      {children}
      </div>
     
        </div>
      </body>
    </html>
  )
}
