import Navbar from '@/components/navbar/page'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  manifest: "/manifest.json",
  title: 'Portfolio Ivana Kowalczuk',
  description: 'Generated by create next app',
  viewport: "width=device-width, initial-scale=1.0",
  icons:{
    apple: "/icon.png"
  },
  themeColor: "#000"

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
 
    <html  lang="es">
      <body className='flex flex-col w-full h-screen'>
        <Navbar/>
        <div className='m-auto lg:w-11/12 h-full'>
        <Providers >
        {children}
        </Providers>
        </div>
      </body>
    </html>
   
  )
}
